# Generated by Django 4.0 on 2021-12-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main_Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('Subscribe_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('User_email_Address', models.CharField(max_length=100)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Menu.category')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('Newsletter_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Newsletter_Type', models.CharField(max_length=100)),
                ('email_list', models.CharField(max_length=100)),
                ('Newsletter_Message', models.CharField(max_length=100)),
                ('Category_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main_Menu.category')),
            ],
        ),
    ]
