# Generated by Django 4.0 on 2021-12-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainmenu',
            fields=[
                ('menuid', models.IntegerField(primary_key=True, serialize=False)),
                ('menuname', models.CharField(max_length=50)),
                ('menutype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('menuname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_Menu.mainmenu')),
            ],
        ),
    ]
