# Generated by Django 4.0 on 2021-12-22 17:32

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('Blog_id', models.IntegerField(default=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('<django.db.models.fields.IntegerField>', 'Category Id'), ('world', 'World'), ('technology', 'Technology'), ('environment', 'Environment'), ('science', 'Science'), ('programming', 'Programming'), ('travel', 'Travel')], default='world', max_length=50)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=3)),
                ('content', ckeditor.fields.RichTextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('Comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Comment', models.TextField(max_length=100)),
                ('Blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='Post_comment.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyModel',
            fields=[
                ('Reply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Reply_message', models.TextField(max_length=100)),
                ('Blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogModel', to='Post_comment.blogpost')),
                ('Comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Post_comment.commentmodel')),
            ],
        ),
    ]
